### ISSUE TITLE
Ordering of properties in json lists

### ISSUE THREAD

**Issue by ksallberg** [futurice/space-tyckiting#14]
Hello!

I have noticed that the ordering of certain JSON objects is not always the same. I have run into the issue that sometimes y comes before x in position tuples. But most often x comes before y. In the erlang client, I assumed that the order is fixed.

I see that this might not be a problem for clients that use object.x, object.y to parse. But when using pattern matching to parse it is a problem.

Should the clients be able to parse JSON objects with any internal order?

It would be helpful if you can explain a bit what guarantees there are for internal ordering of your JSON objects...

For instance, can something like this happen? Order 1 of events type object:

```
{
    "type": "events",
    "roundId": <the id of round>,
    "config": <configuration object>,
    "you": <team information>,
    "otherTeams": [<array of other teams>],
    "events": <array of events>
}
```

Order 1 of events type object:

```
{
    "roundId": <the id of round>,
    "events": <array of events>
    "type": "events",
    "you": <team information>,
    "otherTeams": [<array of other teams>],
    "config": <configuration object>,
}
```

**Comment by seance** [comment]
I don't think there are any guarantees on ordering. Could you use some kind of sorting before pattern matching?

**Comment by ksallberg** [comment]
Ok thanks for the reply, clients will have to work no matter the ordering of JSON list instances.
