### ISSUE TITLE
Bad separation of AI and UI

### ISSUE THREAD

**Issue by Deraen** [futurice/space-tyckiting#5]
Because AI is started by UI client, the AI has to be implemented in JS even though WebSockets would provide API accessible from nearly any language *.
Client could be a separate app requesting the state of game from server.

```
                  +----+
+--------+        | AI |
|        +--------+----+
| Server |  WS          
|        +--------+----+
+---+----+        | AI |
    |             +----+
    |                   
    |WS                 
    |                   
    |                   
+---+----+              
|        |              
| Client |              
|        |              
+--------+              
```

Also the server URL is hard coded to client so this makes it harder to test AI's against other teams. If AI could be told to connect to specific server it would be possible to organize competitions by telling people to connect to specific server and thus teams wouldn't have to send files over email/usb stick/git.

*) Socket.io is in practice JS only but JSON over plain WS should work for this app.

**Comment by kimmobrunfeldt** [comment]
Yeah, exactly :) This is a known issue but schedule was tight.

We'll separate the UI at some point if we use this game again internally.

**Comment by okajasto** [comment]
Yep. Valid points and as Kimmo already mentioned will be fixed in next iteration.

**Comment by Deraen** [comment]
I'm closing this as I don't want to have this hanging around on my list of open issues.

**Comment by kimmobrunfeldt** [comment]
:+1:
